"""empty message

Revision ID: 251ae6c1b2fb
Revises: c4062877857d
Create Date: 2025-05-28 16:16:58.635655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "251ae6c1b2fb"
down_revision: Union[str, None] = "c4062877857d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track_features", sa.Column("spectral_flatness_mean", sa.Float(), nullable=False))
    op.add_column("track_features", sa.Column("spectral_flatness_var", sa.Float(), nullable=False))
    op.add_column("track_features", sa.Column("harmonic_percussive_ratio", sa.Float(), nullable=False))
    op.add_column("track_features", sa.Column("mel_entropy_mean", sa.Float(), nullable=False))
    op.add_column("track_features", sa.Column("mel_entropy_var", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track_features", "mel_entropy_var")
    op.drop_column("track_features", "mel_entropy_mean")
    op.drop_column("track_features", "harmonic_percussive_ratio")
    op.drop_column("track_features", "spectral_flatness_var")
    op.drop_column("track_features", "spectral_flatness_mean")
    # ### end Alembic commands ###
