"""change playlists.traks_amount to playlists.tracks_amount

Revision ID: 53f5bffe60e3
Revises: 8fb5445fcceb
Create Date: 2025-05-10 14:13:47.493922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53f5bffe60e3"
down_revision: Union[str, None] = "8fb5445fcceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlists", "tracks_amount")
    op.add_column("playlists", sa.Column("tracks_amount", sa.Integer(), nullable=True, insert_default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlists", "tracks_amount")
    op.add_column("playlists", sa.Column("tracks_amount", sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
