"""empty message

Revision ID: 56eaf928ef8c
Revises: efe57a63c824
Create Date: 2025-05-19 19:51:31.308815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56eaf928ef8c'
down_revision: Union[str, None] = 'efe57a63c824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playlists_name', table_name='playlists')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_playlists_name', 'playlists', ['name'], unique=True)
    # ### end Alembic commands ###
