"""change playlists.traks_amount to playlists.tracks_amount

Revision ID: 8fb5445fcceb
Revises: c1de847e26b4
Create Date: 2025-05-10 14:09:06.826030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fb5445fcceb"
down_revision: Union[str, None] = "c1de847e26b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playlists", sa.Column("tracks_amount", sa.Integer(), nullable=True, default=0))
    op.drop_column("playlists", "traks_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playlists", sa.Column("traks_amount", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("playlists", "tracks_amount")
    # ### end Alembic commands ###
