"""empty message

Revision ID: c4062877857d
Revises: 56eaf928ef8c
Create Date: 2025-05-20 12:30:00.464808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4062877857d"
down_revision: Union[str, None] = "56eaf928ef8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracks_stat",
        sa.Column("yt_id", sa.String(length=25), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("track_playback", sa.Integer(), nullable=False, default=1),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["yt_id"],
            ["tracks.yt_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracks_stat_id"), "tracks_stat", ["id"], unique=True)
    op.create_index(op.f("ix_tracks_stat_updated_at"), "tracks_stat", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracks_stat_updated_at"), table_name="tracks_stat")
    op.drop_index(op.f("ix_tracks_stat_id"), table_name="tracks_stat")
    op.drop_table("tracks_stat")
    # ### end Alembic commands ###
