"""add TrackFeatures

Revision ID: efe57a63c824
Revises: 53f5bffe60e3
Create Date: 2025-05-15 17:05:21.031787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe57a63c824'
down_revision: Union[str, None] = '53f5bffe60e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_features',
    sa.Column('yt_id', sa.String(), nullable=False),
    sa.Column('chroma_mean', sa.Float(), nullable=False),
    sa.Column('chroma_var', sa.Float(), nullable=False),
    sa.Column('rms_mean', sa.Float(), nullable=False),
    sa.Column('rms_var', sa.Float(), nullable=False),
    sa.Column('spectral_centroids_mean', sa.Float(), nullable=False),
    sa.Column('spectral_centroids_var', sa.Float(), nullable=False),
    sa.Column('spectral_bandwidth_mean', sa.Float(), nullable=False),
    sa.Column('spectral_bandwidth_var', sa.Float(), nullable=False),
    sa.Column('spectral_rolloff_mean', sa.Float(), nullable=False),
    sa.Column('spectral_rolloff_var', sa.Float(), nullable=False),
    sa.Column('spectral_contrast_mean', sa.Float(), nullable=False),
    sa.Column('spectral_contrast_var', sa.Float(), nullable=False),
    sa.Column('zero_crossing_rate_mean', sa.Float(), nullable=False),
    sa.Column('zero_crossing_rate_var', sa.Float(), nullable=False),
    sa.Column('tempo', sa.Float(), nullable=False),
    sa.Column('mfcc_1_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_1_var', sa.Float(), nullable=False),
    sa.Column('mfcc_2_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_2_var', sa.Float(), nullable=False),
    sa.Column('mfcc_3_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_3_var', sa.Float(), nullable=False),
    sa.Column('mfcc_4_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_4_var', sa.Float(), nullable=False),
    sa.Column('mfcc_5_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_5_var', sa.Float(), nullable=False),
    sa.Column('mfcc_6_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_6_var', sa.Float(), nullable=False),
    sa.Column('mfcc_7_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_7_var', sa.Float(), nullable=False),
    sa.Column('mfcc_8_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_8_var', sa.Float(), nullable=False),
    sa.Column('mfcc_9_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_9_var', sa.Float(), nullable=False),
    sa.Column('mfcc_10_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_10_var', sa.Float(), nullable=False),
    sa.Column('mfcc_11_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_11_var', sa.Float(), nullable=False),
    sa.Column('mfcc_12_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_12_var', sa.Float(), nullable=False),
    sa.Column('mfcc_13_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_13_var', sa.Float(), nullable=False),
    sa.Column('mfcc_14_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_14_var', sa.Float(), nullable=False),
    sa.Column('mfcc_15_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_15_var', sa.Float(), nullable=False),
    sa.Column('mfcc_16_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_16_var', sa.Float(), nullable=False),
    sa.Column('mfcc_17_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_17_var', sa.Float(), nullable=False),
    sa.Column('mfcc_18_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_18_var', sa.Float(), nullable=False),
    sa.Column('mfcc_19_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_19_var', sa.Float(), nullable=False),
    sa.Column('mfcc_20_mean', sa.Float(), nullable=False),
    sa.Column('mfcc_20_var', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['yt_id'], ['tracks.yt_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_features_id'), 'track_features', ['id'], unique=True)
    op.create_index(op.f('ix_track_features_updated_at'), 'track_features', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_features_updated_at'), table_name='track_features')
    op.drop_index(op.f('ix_track_features_id'), table_name='track_features')
    op.drop_table('track_features')
    # ### end Alembic commands ###
